# docker-compose.yml
version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: igreja-db
    restart: always
    environment:
      POSTGRES_DB: igreja_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Lp11Baluarte
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

