version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: local_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot_container
    environment:
      DB_URL: jdbc:mysql://mysql:3306/appdb
      DB_USERNAME: appuser
      DB_PASSWORD: apppassword
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:

